# Generated by Django 2.1.5 on 2019-04-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
